version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ostarius"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-oryhm022mkbj"
s3_prefix = "ostarius"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
